spring:
  profiles:
    default: dev

  application:
    name: vollmed_api

server:
  servlet:
    context-path: /vollmed
  error:
    include-stacktrace: never

  mvc:
    servlet:
      path: /api



