spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

api:
  security:
    token:
      secret: ${JWT_SECRET}
      issuer: vollmed_api
